services:
  caddy:
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile    
  mongodb:
    ports:
      - "27018:27017"
  taskmaster-server:
    container_name: taskmaster-server
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:3001"
    command: npm run prod