services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.7
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27018
    networks:
      - taskmaster-server
  caddy:
    container_name: caddy
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - 8080:8080
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - taskmaster-server
  taskmaster-server:
    container_name: taskmaster-server-dev
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/taskmaster/app/src
      - ./nodemon.json:/taskmaster/app/nodemon.json
    env_file:
      - .env.dev
    ports:
      - 3000:3000
      - 3001
    networks:
      - taskmaster-server
volumes:
  caddy_data:
  caddy_config:
  mongodb:
networks:
  taskmaster-server: